### ISSUE TITLE
Crypto issue

### ISSUE THREAD

**Issue by phiificodes** [phiificodes/indexedDB_encryption_bundler#1]
With the bundle approach, the same error occurs 
Uncaught TypeError: crypto.generateKeyPairSync is not a function
    at bundle.js:59:40

@joacopaz Kindly look this up. I think I lack some know-how working with the crypto module. Thanks

**Comment by joacopaz** [comment]
I submitted https://github.com/phiificodes/indexedDB_encryption/pull/2
